logging:
  pattern:
    dateformat: MM-dd HH:mm:ss

spring:
  rabbitmq:
    host: 192.168.137.105 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: root # 用户名
    password: root # 密码
